### ISSUE TITLE
does not close android app by pressing back button 

### ISSUE THREAD

**Issue by pritam148** [City-of-Bloomington/open311-android#63]

**Comment by milovanderlinden** [comment]
I got the feeling this is due to the fact that on the MainActivity, 
```
startActivity(intent);
```

Is blocking access to the startupscreen (with the logo) because it will constantly try to forward into the Services list. Commenting that line (MainActivity.java line:105) will stop this behaviour and will let you exit the application again by pressing the back button.

```
//startActivity(intent);
```

This does however mean that a user always needs to click the logo page to get to the services list.

Would that be acceptable?

**Comment by inghamn** [comment]
Maybe the logo splash screen is not needed. 

We were wanting to show the user what city they are currently reporting to.  Although, I really don't know how much of a use case that is.  I think most versions of this app get recompiled as a single-city version.

**Comment by milovanderlinden** [comment]
I agree.
